description: wikitext

target:
  service: aml
  # name: tscience-a100-80g-eastus
  name: A100-80G-PCIE-westus3
  # name: V10032G
  # name: A100EastUS
  # name: openai-A10080G
  # name: A10080G
  # name: gpu-v100-32g
  # name: gpu-a100-80g


environment:
  image: pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
  image_setup:
    - apt-get -y update
    - apt-get -y install wget
    - apt-get -y install git
    - apt-get -y install git-lfs
  setup:
    - pip install transformers==4.31
    - pip install accelerate==0.23
    - pip install git+https://github.com/huggingface/peft
    - pip install evaluate scikit-learn scipy typing_extensions einops
    - pip install datasets sentencepiece setuptools rouge-score nltk openai
    - pip install tensorboard tensorboardX
    - pip install bitsandbytes

storage:
  output:
    storage_account_name: tsinterns
    container_name: t-qingzhang
    mount_dir: /mnt/t-qingzhang

code:
  local_dir: ../

jobs:

- name: wikitext_llama2_7b
  sku: 1xG4
  process_count_per_node: 1
  submit_args:
    container_args:
      cpus: 32
  command:
#    - accelerate launch train_clm.py --fake_quantization --model_name_or_path LoftQ/Llama-2-7b-hf-bit4-rank64 --output_dir /mnt/t-qingzhang/exp_results/wikitext-2/bit4-rank64_eval --dataset_name wikitext --dataset_config wikitext-2-raw-v1 2 --per_device_train_batch_size 1 --per_device_eval_batch_size 4 --gradient_accumulation_steps 8 --do_eval --evaluation_strategy epoch --report_to tensorboard --overwrite_output_dir --block_size 512
#    - accelerate launch train_clm.py --model_name_or_path LoftQ/Llama-2-7b-hf-bit4-rank64 --output_dir /mnt/t-qingzhang/exp_results/wikitext-2/bit4-rank64_eval --dataset_name wikitext --dataset_config wikitext-2-raw-v1 2 --per_device_train_batch_size 1 --per_device_eval_batch_size 4 --gradient_accumulation_steps 8 --do_eval --evaluation_strategy epoch --report_to tensorboard --overwrite_output_dir --block_size 512

#    - accelerate launch train_clm.py --fake_quantization --model_name_or_path LoftQ/Llama-2-7b-hf-bit4-rank64 --output_dir /mnt/t-qingzhang/exp_results/wikitext-2/bit4-rank64_ft --learning_rate 1e-4  --seed 202 --dataset_name wikitext --dataset_config wikitext-2-raw-v1 --num_train_epochs 2 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --do_train --do_eval --logging_steps 50 --save_steps 1000000 --evaluation_strategy epoch --report_to tensorboard --overwrite_output_dir --block_size 512
    - python train_clm.py --model_name_or_path LoftQ/Llama-2-7b-hf-bit4-rank64 --output_dir /mnt/t-qingzhang/exp_results/wikitext-2/bit4-rank64_ft --learning_rate 1e-4  --seed 202 --dataset_name wikitext --dataset_config wikitext-2-raw-v1 --num_train_epochs 2 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --do_train --do_eval --logging_steps 50 --save_steps 1000000 --evaluation_strategy epoch --report_to tensorboard --overwrite_output_dir --block_size 512

